### ISSUE TITLE
作者你好，可以加你联系方式询问问题吗（有偿）

### ISSUE THREAD

**Issue by mikasa7jay** [AthBe1337/UESTC-Forum#1]

**Comment by AthBe1337** [comment]
你好，有问题可以直接问。有别的事可以联系AthBe1337@gmail.com。

**Comment by mikasa7jay** [comment]
怎么使用脚本。已经安装那个库，chrome drivers也装了。但是怎么使用嘞

**Comment by AthBe1337** [comment]
> 怎么使用脚本。已经安装那个库，chrome drivers也装了。但是怎么使用嘞

在命令行中切换到脚本所在目录，然后输入

python main.py [参数]

具体参数参考readme
